/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as ActualitesRouteImport } from './routes/actualites'
import { Route as AdmissionRouteImport } from './routes/admission'
import { Route as AlumniRouteImport } from './routes/alumni'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CoursADistanceRouteImport } from './routes/cours-a-distance'
import { Route as EtudiezAuGhanaRouteImport } from './routes/etudiez-au-ghana'
import { Route as GalerieRouteImport } from './routes/galerie'
import { Route as HistoriqueRouteImport } from './routes/historique'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as MemoiresRechercheRouteImport } from './routes/memoires-recherche'
import { Route as MotsDuPresidentRouteImport } from './routes/mots-du-president'
import { Route as OrientationRouteImport } from './routes/orientation'
import { Route as PourquoiFopaseRouteImport } from './routes/pourquoi-fopase'
import { Route as ResultatsAnnuelsRouteImport } from './routes/resultats-annuels'
import { Route as VieEtudianteRouteImport } from './routes/vie-etudiante'
import { Route as FormationsIndexRouteImport } from './routes/formations.index'
import { Route as FormationsSlugRouteImport } from './routes/formations.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesRoute = ActualitesRouteImport.update({
  id: '/actualites',
  path: '/actualites',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionRoute = AdmissionRouteImport.update({
  id: '/admission',
  path: '/admission',
  getParentRoute: () => rootRouteImport,
} as any)
const AlumniRoute = AlumniRouteImport.update({
  id: '/alumni',
  path: '/alumni',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursADistanceRoute = CoursADistanceRouteImport.update({
  id: '/cours-a-distance',
  path: '/cours-a-distance',
  getParentRoute: () => rootRouteImport,
} as any)
const EtudiezAuGhanaRoute = EtudiezAuGhanaRouteImport.update({
  id: '/etudiez-au-ghana',
  path: '/etudiez-au-ghana',
  getParentRoute: () => rootRouteImport,
} as any)
const GalerieRoute = GalerieRouteImport.update({
  id: '/galerie',
  path: '/galerie',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriqueRoute = HistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoiresRechercheRoute = MemoiresRechercheRouteImport.update({
  id: '/memoires-recherche',
  path: '/memoires-recherche',
  getParentRoute: () => rootRouteImport,
} as any)
const MotsDuPresidentRoute = MotsDuPresidentRouteImport.update({
  id: '/mots-du-president',
  path: '/mots-du-president',
  getParentRoute: () => rootRouteImport,
} as any)
const OrientationRoute = OrientationRouteImport.update({
  id: '/orientation',
  path: '/orientation',
  getParentRoute: () => rootRouteImport,
} as any)
const PourquoiFopaseRoute = PourquoiFopaseRouteImport.update({
  id: '/pourquoi-fopase',
  path: '/pourquoi-fopase',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultatsAnnuelsRoute = ResultatsAnnuelsRouteImport.update({
  id: '/resultats-annuels',
  path: '/resultats-annuels',
  getParentRoute: () => rootRouteImport,
} as any)
const VieEtudianteRoute = VieEtudianteRouteImport.update({
  id: '/vie-etudiante',
  path: '/vie-etudiante',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationsIndexRoute = FormationsIndexRouteImport.update({
  id: '/formations/',
  path: '/formations/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationsSlugRoute = FormationsSlugRouteImport.update({
  id: '/formations/$slug',
  path: '/formations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/actualites': typeof ActualitesRoute
  '/admission': typeof AdmissionRoute
  '/alumni': typeof AlumniRoute
  '/contact': typeof ContactRoute
  '/cours-a-distance': typeof CoursADistanceRoute
  '/etudiez-au-ghana': typeof EtudiezAuGhanaRoute
  '/galerie': typeof GalerieRoute
  '/historique': typeof HistoriqueRoute
  '/inscription': typeof InscriptionRoute
  '/memoires-recherche': typeof MemoiresRechercheRoute
  '/mots-du-president': typeof MotsDuPresidentRoute
  '/orientation': typeof OrientationRoute
  '/pourquoi-fopase': typeof PourquoiFopaseRoute
  '/resultats-annuels': typeof ResultatsAnnuelsRoute
  '/vie-etudiante': typeof VieEtudianteRoute
  '/formations/$slug': typeof FormationsSlugRoute
  '/formations/': typeof FormationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/actualites': typeof ActualitesRoute
  '/admission': typeof AdmissionRoute
  '/alumni': typeof AlumniRoute
  '/contact': typeof ContactRoute
  '/cours-a-distance': typeof CoursADistanceRoute
  '/etudiez-au-ghana': typeof EtudiezAuGhanaRoute
  '/galerie': typeof GalerieRoute
  '/historique': typeof HistoriqueRoute
  '/inscription': typeof InscriptionRoute
  '/memoires-recherche': typeof MemoiresRechercheRoute
  '/mots-du-president': typeof MotsDuPresidentRoute
  '/orientation': typeof OrientationRoute
  '/pourquoi-fopase': typeof PourquoiFopaseRoute
  '/resultats-annuels': typeof ResultatsAnnuelsRoute
  '/vie-etudiante': typeof VieEtudianteRoute
  '/formations/$slug': typeof FormationsSlugRoute
  '/formations': typeof FormationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/actualites': typeof ActualitesRoute
  '/admission': typeof AdmissionRoute
  '/alumni': typeof AlumniRoute
  '/contact': typeof ContactRoute
  '/cours-a-distance': typeof CoursADistanceRoute
  '/etudiez-au-ghana': typeof EtudiezAuGhanaRoute
  '/galerie': typeof GalerieRoute
  '/historique': typeof HistoriqueRoute
  '/inscription': typeof InscriptionRoute
  '/memoires-recherche': typeof MemoiresRechercheRoute
  '/mots-du-president': typeof MotsDuPresidentRoute
  '/orientation': typeof OrientationRoute
  '/pourquoi-fopase': typeof PourquoiFopaseRoute
  '/resultats-annuels': typeof ResultatsAnnuelsRoute
  '/vie-etudiante': typeof VieEtudianteRoute
  '/formations/$slug': typeof FormationsSlugRoute
  '/formations/': typeof FormationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/actualites'
    | '/admission'
    | '/alumni'
    | '/contact'
    | '/cours-a-distance'
    | '/etudiez-au-ghana'
    | '/galerie'
    | '/historique'
    | '/inscription'
    | '/memoires-recherche'
    | '/mots-du-president'
    | '/orientation'
    | '/pourquoi-fopase'
    | '/resultats-annuels'
    | '/vie-etudiante'
    | '/formations/$slug'
    | '/formations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/actualites'
    | '/admission'
    | '/alumni'
    | '/contact'
    | '/cours-a-distance'
    | '/etudiez-au-ghana'
    | '/galerie'
    | '/historique'
    | '/inscription'
    | '/memoires-recherche'
    | '/mots-du-president'
    | '/orientation'
    | '/pourquoi-fopase'
    | '/resultats-annuels'
    | '/vie-etudiante'
    | '/formations/$slug'
    | '/formations'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/actualites'
    | '/admission'
    | '/alumni'
    | '/contact'
    | '/cours-a-distance'
    | '/etudiez-au-ghana'
    | '/galerie'
    | '/historique'
    | '/inscription'
    | '/memoires-recherche'
    | '/mots-du-president'
    | '/orientation'
    | '/pourquoi-fopase'
    | '/resultats-annuels'
    | '/vie-etudiante'
    | '/formations/$slug'
    | '/formations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  ActualitesRoute: typeof ActualitesRoute
  AdmissionRoute: typeof AdmissionRoute
  AlumniRoute: typeof AlumniRoute
  ContactRoute: typeof ContactRoute
  CoursADistanceRoute: typeof CoursADistanceRoute
  EtudiezAuGhanaRoute: typeof EtudiezAuGhanaRoute
  GalerieRoute: typeof GalerieRoute
  HistoriqueRoute: typeof HistoriqueRoute
  InscriptionRoute: typeof InscriptionRoute
  MemoiresRechercheRoute: typeof MemoiresRechercheRoute
  MotsDuPresidentRoute: typeof MotsDuPresidentRoute
  OrientationRoute: typeof OrientationRoute
  PourquoiFopaseRoute: typeof PourquoiFopaseRoute
  ResultatsAnnuelsRoute: typeof ResultatsAnnuelsRoute
  VieEtudianteRoute: typeof VieEtudianteRoute
  FormationsSlugRoute: typeof FormationsSlugRoute
  FormationsIndexRoute: typeof FormationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites': {
      id: '/actualites'
      path: '/actualites'
      fullPath: '/actualites'
      preLoaderRoute: typeof ActualitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admission': {
      id: '/admission'
      path: '/admission'
      fullPath: '/admission'
      preLoaderRoute: typeof AdmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumni': {
      id: '/alumni'
      path: '/alumni'
      fullPath: '/alumni'
      preLoaderRoute: typeof AlumniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cours-a-distance': {
      id: '/cours-a-distance'
      path: '/cours-a-distance'
      fullPath: '/cours-a-distance'
      preLoaderRoute: typeof CoursADistanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etudiez-au-ghana': {
      id: '/etudiez-au-ghana'
      path: '/etudiez-au-ghana'
      fullPath: '/etudiez-au-ghana'
      preLoaderRoute: typeof EtudiezAuGhanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galerie': {
      id: '/galerie'
      path: '/galerie'
      fullPath: '/galerie'
      preLoaderRoute: typeof GalerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historique': {
      id: '/historique'
      path: '/historique'
      fullPath: '/historique'
      preLoaderRoute: typeof HistoriqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memoires-recherche': {
      id: '/memoires-recherche'
      path: '/memoires-recherche'
      fullPath: '/memoires-recherche'
      preLoaderRoute: typeof MemoiresRechercheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mots-du-president': {
      id: '/mots-du-president'
      path: '/mots-du-president'
      fullPath: '/mots-du-president'
      preLoaderRoute: typeof MotsDuPresidentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orientation': {
      id: '/orientation'
      path: '/orientation'
      fullPath: '/orientation'
      preLoaderRoute: typeof OrientationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pourquoi-fopase': {
      id: '/pourquoi-fopase'
      path: '/pourquoi-fopase'
      fullPath: '/pourquoi-fopase'
      preLoaderRoute: typeof PourquoiFopaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultats-annuels': {
      id: '/resultats-annuels'
      path: '/resultats-annuels'
      fullPath: '/resultats-annuels'
      preLoaderRoute: typeof ResultatsAnnuelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vie-etudiante': {
      id: '/vie-etudiante'
      path: '/vie-etudiante'
      fullPath: '/vie-etudiante'
      preLoaderRoute: typeof VieEtudianteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formations/': {
      id: '/formations/'
      path: '/formations'
      fullPath: '/formations/'
      preLoaderRoute: typeof FormationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formations/$slug': {
      id: '/formations/$slug'
      path: '/formations/$slug'
      fullPath: '/formations/$slug'
      preLoaderRoute: typeof FormationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  ActualitesRoute: ActualitesRoute,
  AdmissionRoute: AdmissionRoute,
  AlumniRoute: AlumniRoute,
  ContactRoute: ContactRoute,
  CoursADistanceRoute: CoursADistanceRoute,
  EtudiezAuGhanaRoute: EtudiezAuGhanaRoute,
  GalerieRoute: GalerieRoute,
  HistoriqueRoute: HistoriqueRoute,
  InscriptionRoute: InscriptionRoute,
  MemoiresRechercheRoute: MemoiresRechercheRoute,
  MotsDuPresidentRoute: MotsDuPresidentRoute,
  OrientationRoute: OrientationRoute,
  PourquoiFopaseRoute: PourquoiFopaseRoute,
  ResultatsAnnuelsRoute: ResultatsAnnuelsRoute,
  VieEtudianteRoute: VieEtudianteRoute,
  FormationsSlugRoute: FormationsSlugRoute,
  FormationsIndexRoute: FormationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
